# -*- coding: utf-8 -*-
"""Depth estimation and deblurring.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uvfTQyubDlUPmWfn0evZEo9zzYWOE2T-
"""

from google.colab import files
uploaded = files.upload()  # Upload new far.jpg and near.jpg

# Re-load the images
import cv2
img_near = cv2.imread('near.jpg')
img_far = cv2.imread('far.jpg')

!pip install numpy==1.23.5 opencv-contrib-python==4.5.5.64

import cv2
import numpy as np
import matplotlib.pyplot as plt  # <- Missing before

# Load uploaded images
near_img = cv2.imread('near.jpg', cv2.IMREAD_GRAYSCALE)
far_img = cv2.imread('far.jpg', cv2.IMREAD_GRAYSCALE)

# Display for confirmation
plt.figure(figsize=(10, 5))

plt.subplot(1, 2, 1)
plt.imshow(near_img, cmap='gray')
plt.title("Near Image")
plt.axis('off')

plt.subplot(1, 2, 2)
plt.imshow(far_img, cmap='gray')
plt.title("Far Image")
plt.axis('off')

plt.tight_layout()
plt.show()

import cv2
import numpy as np
import matplotlib.pyplot as plt
from cv2.ximgproc import guidedFilter

# -------- Load Near and Far Focused Images --------
img_near = cv2.imread('near.jpg')  # Near-focused image
img_far = cv2.imread('far.jpg')    # Far-focused image
gray_far = cv2.cvtColor(img_far, cv2.COLOR_BGR2GRAY)

# -------- SIFT-Based Alignment --------
def align_images_sift(img1, img2):
    """
    Aligns img1 to img2 using SIFT and homography transformation.
    """
    gray1 = cv2.cvtColor(img1, cv2.COLOR_BGR2GRAY)
    gray2 = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)

    sift = cv2.SIFT_create()
    kp1, des1 = sift.detectAndCompute(gray1, None)
    kp2, des2 = sift.detectAndCompute(gray2, None)

    # Use FLANN-based matcher
    index_params = dict(algorithm=1, trees=5)
    search_params = dict()
    flann = cv2.FlannBasedMatcher(index_params, search_params)
    matches = flann.knnMatch(des1, des2, k=2)

    # Lowe's ratio test
    good_matches = [m for m, n in matches if m.distance < 0.75 * n.distance]

    if len(good_matches) >= 10:
        src_pts = np.float32([kp1[m.queryIdx].pt for m in good_matches]).reshape(-1, 1, 2)
        dst_pts = np.float32([kp2[m.trainIdx].pt for m in good_matches]).reshape(-1, 1, 2)
        H, _ = cv2.findHomography(src_pts, dst_pts, cv2.RANSAC, 5.0)
        aligned = cv2.warpPerspective(img1, H, (img2.shape[1], img2.shape[0]))
        return aligned
    else:
        print("Not enough matches to align.")
        return img1  # fallback

# Align the near image to far image
aligned_near = align_images_sift(img_near, img_far)
gray_aligned_near = cv2.cvtColor(aligned_near, cv2.COLOR_BGR2GRAY)

# -------- Sharpness Estimation Function --------
def estimate_sharpness(img):
    """
    Estimates sharpness using the absolute Laplacian.
    """
    lap = cv2.Laplacian(img, cv2.CV_64F)
    return np.abs(lap)

# -------- Depth Map Estimation --------
def estimate_depth_map(gray_near, gray_far, guidance_img):
    """
    Estimates relative depth using sharpness difference and smooths it.
    """
    sharp_near = estimate_sharpness(gray_near)
    sharp_far = estimate_sharpness(gray_far)

    raw_depth = sharp_far - sharp_near

    depth_norm = cv2.normalize(raw_depth, None, 0, 255, cv2.NORM_MINMAX).astype(np.uint8)
    guided_depth = guidedFilter(guidance_img, depth_norm, radius=8, eps=500)
    return guided_depth

# Estimate depth map
depth_map = estimate_depth_map(gray_aligned_near, gray_far, gray_aligned_near)

# -------- All-in-Focus Image --------
def construct_all_in_focus_image(img_near, img_far):
    """
    Combines sharper regions from both images to make all-in-focus image.
    """
    gray_near = cv2.cvtColor(img_near, cv2.COLOR_BGR2GRAY)
    gray_far = cv2.cvtColor(img_far, cv2.COLOR_BGR2GRAY)

    sharp_near = estimate_sharpness(gray_near)
    sharp_far = estimate_sharpness(gray_far)

    mask = (sharp_near > sharp_far).astype(np.float32)
    mask = cv2.GaussianBlur(mask, (9, 9), 0)
    mask_3ch = np.repeat(mask[:, :, np.newaxis], 3, axis=2)

    fused = (img_near * mask_3ch + img_far * (1 - mask_3ch)).astype(np.uint8)
    return fused

# Create all-in-focus image
all_in_focus = construct_all_in_focus_image(aligned_near, img_far)

# -------- Display Results --------
plt.figure(figsize=(18, 6))
plt.subplot(1, 3, 1)
plt.title("Aligned Near Focus")
plt.imshow(cv2.cvtColor(aligned_near, cv2.COLOR_BGR2RGB))
plt.axis('off')

plt.subplot(1, 3, 2)
plt.title("Far Focus")
plt.imshow(cv2.cvtColor(img_far, cv2.COLOR_BGR2RGB))
plt.axis('off')

plt.subplot(1, 3, 3)
plt.title("Depth Map")
plt.imshow(depth_map, cmap='jet')
plt.axis('off')
plt.show()

plt.figure(figsize=(6, 6))
plt.title("All-in-Focus Image")
plt.imshow(cv2.cvtColor(all_in_focus, cv2.COLOR_BGR2RGB))
plt.axis('off')
plt.show()

from google.colab import files

uploaded = files.upload()

# Load Ground Truth Depth Map
deblur = cv2.imread('deblur.jpg', cv2.IMREAD_GRAYSCALE)

# Check if image is loaded
if deblur is None:
    print("Error: Ground truth depth map not found or failed to load. Please check the filename/path.")
else:
    # Resize only if image is loaded
    deblur = cv2.resize(deblur, (deblur.shape[1], deblur.shape[0]))

from skimage.metrics import structural_similarity as ssim
import matplotlib.pyplot as plt

# Load captured AIF image
aif_true = cv2.imread('deblur.jpg')
aif_true = cv2.resize(aif_true, (all_in_focus.shape[1], all_in_focus.shape[0]))

# Normalize for RMS
aif_pred_norm = all_in_focus.astype(np.float32) / 255.0
aif_true_norm = aif_true.astype(np.float32) / 255.0

# Compute RMS Error
rms_error = np.sqrt(np.mean((aif_pred_norm - aif_true_norm) ** 2))
print("🔹 RMS Error (Color) between constructed AIF and captured AIF:", rms_error)

# Convert to grayscale for SSIM
gray_pred = cv2.cvtColor((aif_pred_norm * 255).astype(np.uint8), cv2.COLOR_BGR2GRAY)
gray_true = cv2.cvtColor((aif_true_norm * 255).astype(np.uint8), cv2.COLOR_BGR2GRAY)

# Compute SSIM
ssim_score, _ = ssim(gray_pred, gray_true, full=True)
print("🔸 SSIM (Grayscale) between constructed AIF and captured AIF:", ssim_score)

# Save constructed AIF if needed
cv2.imwrite('constructed_aif.png', all_in_focus)

# -------- Visualization --------
plt.figure(figsize=(15, 6))

plt.subplot(1, 2, 1)
plt.title("Captured AIF (deblur.jpg)")
plt.imshow(cv2.cvtColor(aif_true, cv2.COLOR_BGR2RGB))
plt.axis('off')

plt.subplot(1, 2, 2)
plt.title(f"Constructed AIF\nRMS: {rms_error:.4f} | SSIM: {ssim_score:.4f}")
plt.imshow(cv2.cvtColor(all_in_focus, cv2.COLOR_BGR2RGB))
plt.axis('off')

plt.suptitle("Constructed vs Captured AIF Comparison", fontsize=16)
plt.tight_layout()
plt.show()

from google.colab import files
uploaded = files.upload()

import cv2
import numpy as np

# Load the AIF image (deblur image)
deblur = cv2.imread('deblur.jpg')
if deblur is None:
    raise FileNotFoundError("Error: 'deblur.jpg' not found or cannot be loaded.")

# Convert to grayscale
gray_deblur = cv2.cvtColor(deblur, cv2.COLOR_BGR2GRAY)

# Estimate sharpness on the AIF image as a proxy for depth
def estimate_sharpness(img):
    lap = cv2.Laplacian(img, cv2.CV_64F)
    return np.abs(lap)

sharp_deblur = estimate_sharpness(gray_deblur)

# Normalize sharpness map for depth estimation
depth_aif = cv2.normalize(sharp_deblur, None, 0, 255, cv2.NORM_MINMAX).astype(np.uint8)

# Now you already have depth_map from your main pipeline (near/far images)
# Make sure both depth maps have the same size
H, W = depth_map.shape[:2]
depth_aif_resized = cv2.resize(depth_aif, (W, H))

# Normalize both depth maps to [0,1] float for error calculation
depth_map_norm = depth_map.astype(np.float32) / 255.0
depth_aif_norm = depth_aif_resized.astype(np.float32) / 255.0

# Calculate RMS error between estimated depth maps
rms_error = np.sqrt(np.mean((depth_map_norm - depth_aif_norm) ** 2))

print(f" RMS Error between depth from AIF sharpness and depth from near/far images: {rms_error:.6f}")

# Optional: visualize comparison
import matplotlib.pyplot as plt

plt.figure(figsize=(18,5))

plt.subplot(1,3,1)
plt.title("Depth Map from Near/Far Images")
plt.imshow(depth_map, cmap='jet')
plt.axis('off')

plt.subplot(1,3,2)
plt.title("Depth Map from AIF Sharpness")
plt.imshow(depth_aif_resized, cmap='jet')
plt.axis('off')

plt.subplot(1,3,3)
plt.title(f"Difference Map\nRMS: {rms_error:.4f}")
diff = np.abs(depth_map_norm - depth_aif_norm)
plt.imshow(diff, cmap='jet')
plt.axis('off')

plt.tight_layout()
plt.show()

# -------- Laplacian Variance Function --------
def laplacian_variance(img):
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    lap = cv2.Laplacian(gray, cv2.CV_64F)
    return lap.var()

# -------- Compute Variance for Each Image --------
img_near = cv2.imread('near.jpg')
img_far = cv2.imread('far.jpg')
constructed_aif = all_in_focus  # from your fusion output

# Resize all to match
H, W = constructed_aif.shape[:2]
img_near = cv2.resize(img_near, (W, H))
img_far = cv2.resize(img_far, (W, H))

var_near = laplacian_variance(img_near)
var_far = laplacian_variance(img_far)
var_aif = laplacian_variance(constructed_aif)

# -------- Print Results --------
print("📈 Laplacian Variance (Sharpness Measure):")
print(f" - Near-focused image:      {var_near:.2f}")
print(f" - Far-focused image:       {var_far:.2f}")
print(f" - Constructed AIF image:   {var_aif:.2f}")